import type { DashboardSummary } from '~/shared/types/admin'

export const mockDashboardData: DashboardSummary = {
  summary_stats: {
    active_projects: 12,
    total_contractors: 8,
    total_tracked_value: 250000,
    open_disputes: 2,
  },
  urgent_actions: {
    new_projects: 3,
    pending_payments: 5,
    disputes: 2,
  },
  recent_projects: [
    {
      id: 'uuid-1',
      project_number: 'P001',
      name: 'مشروع البناء الأول',
      city: 'القاهرة',
      client_name: 'أحمد محمد',
      status: 'active',
      milestones_completed: 2,
      milestones_total: 5,
      progress_percentage: 40,
    },
    {
      id: 'uuid-2',
      project_number: 'P002',
      name: 'مشروع الإسكان الثاني',
      city: 'الجيزة',
      client_name: 'فاطمة علي',
      status: 'in_progress',
      milestones_completed: 3,
      milestones_total: 6,
      progress_percentage: 50,
    },
    {
      id: 'uuid-3',
      project_number: 'P003',
      name: 'مشروع المركز التجاري',
      city: 'الإسكندرية',
      client_name: 'محمد سالم',
      status: 'completed',
      milestones_completed: 4,
      milestones_total: 4,
      progress_percentage: 100,
    },
    {
      id: 'uuid-4',
      project_number: 'P004',
      name: 'مشروع العمارة السكنية',
      city: 'القاهرة',
      client_name: 'سارة خالد',
      status: 'active',
      milestones_completed: 1,
      milestones_total: 5,
      progress_percentage: 20,
    },
    {
      id: 'uuid-5',
      project_number: 'P005',
      name: 'مشروع المستشفى',
      city: 'الرياض',
      client_name: 'علي إبراهيم',
      status: 'under_review',
      milestones_completed: 0,
      milestones_total: 8,
      progress_percentage: 0,
    },
  ],
  open_disputes: [
    {
      id: 'dispute-1',
      dispute_number: 'D001',
      project_name: 'مشروع البناء الأول',
      requester_name: 'علي سالم',
      subject: 'تأخير في التسليم',
      status: 'open',
      created_at: '2026-05-08T10:30:00Z',
    },
    {
      id: 'dispute-2',
      dispute_number: 'D002',
      project_name: 'مشروع الإسكان الثاني',
      requester_name: 'نورا محمود',
      subject: 'عدم الامتثال للمواصفات',
      status: 'mediating',
      created_at: '2026-05-06T14:15:00Z',
    },
  ],
  activity_data: {
    months: [
      'يناير',
      'فبراير',
      'مارس',
      'أبريل',
      'مايو',
      'يونيو',
      'يوليو',
      'أغسطس',
      'سبتمبر',
      'أكتوبر',
      'نوفمبر',
      'ديسمبر',
    ],
    data: [
      { month: 'يناير', milestones: 5, projects: 2 },
      { month: 'فبراير', milestones: 8, projects: 3 },
      { month: 'مارس', milestones: 6, projects: 2 },
      { month: 'أبريل', milestones: 10, projects: 4 },
      { month: 'مايو', milestones: 12, projects: 3 },
      { month: 'يونيو', milestones: 9, projects: 2 },
      { month: 'يوليو', milestones: 14, projects: 5 },
      { month: 'أغسطس', milestones: 11, projects: 3 },
      { month: 'سبتمبر', milestones: 7, projects: 2 },
      { month: 'أكتوبر', milestones: 13, projects: 4 },
      { month: 'نوفمبر', milestones: 8, projects: 2 },
      { month: 'ديسمبر', milestones: 10, projects: 3 },
    ],
  },
  recent_events: [
    {
      id: 'event-1',
      type: 'project_created',
      title: 'مشروع جديد: مشروع البناء الأول',
      timestamp: '2026-05-09T15:30:00Z',
      related_entity_id: 'uuid-1',
    },
    {
      id: 'event-2',
      type: 'milestone_approved',
      title: 'حجر كريم معتمد: الأساسات في مشروع البناء الأول',
      timestamp: '2026-05-08T12:00:00Z',
      related_entity_id: 'uuid-1',
    },
    {
      id: 'event-3',
      type: 'payment_released',
      title: 'دفع أفرج عن: 50000 ريال لـ شركة البناء المتحدة',
      timestamp: '2026-05-07T10:45:00Z',
      related_entity_id: 'uuid-1',
    },
    {
      id: 'event-4',
      type: 'user_created',
      title: 'مستخدم جديد: أحمد علي (مهندس موقع)',
      timestamp: '2026-05-06T09:20:00Z',
    },
    {
      id: 'event-5',
      type: 'milestone_approved',
      title: 'حجر كريم معتمد: الأعمال الكهربائية في مشروع الإسكان',
      timestamp: '2026-05-05T16:30:00Z',
      related_entity_id: 'uuid-2',
    },
  ],
}
