import type { DashboardSummary } from '~/shared/types/admin'

const P001 = '550e8400-e29b-41d4-a716-446655440001'
const P003 = '550e8400-e29b-41d4-a716-446655440003'
const P006 = '550e8400-e29b-41d4-a716-446655440006'
const P011 = '550e8400-e29b-41d4-a716-446655440011'

export const mockDashboardData: DashboardSummary = {
  summary_stats: {
    active_projects: 12,
    milestones_pending_review: 4,
    payments_ready_for_release: 2,
    projects_awaiting_contractor_selection: 3,
    new_users_this_month: 7,
    open_disputes: 2,
  },
  urgent_actions: {
    new_projects: 3,
    pending_payments: 5,
    disputes: 2,
    pending_reports: 4,
  },
  action_queues: {
    open_bidding: [
      {
        id: 'aq-open-1',
        kind: 'open_bidding',
        title: 'إصلاح المدرسة الابتدائية',
        subtitle: 'مشروع جديد — يتطلب فتح باب العروض',
        project_id: P006,
        action_href: `/projects/${P006}`,
        action_label_key: 'admin.dashboard.actions.open_bidding',
      },
      {
        id: 'aq-open-2',
        kind: 'open_bidding',
        title: 'ملعب كرة قدم بالعبور',
        subtitle: 'مشروع جديد — يتطلب فتح باب العروض',
        project_id: P011,
        action_href: `/projects/${P011}`,
        action_label_key: 'admin.dashboard.actions.open_bidding',
      },
    ],
    assign_engineers: [
      {
        id: 'aq-assign-1',
        kind: 'assign_engineers',
        title: 'عمارة سكنية 6 طوابق',
        subtitle: 'تم اختيار المقاول — عيّن مهندس الإشراف ومهندس الموقع',
        project_id: P003,
        action_href: `/projects/${P003}`,
        action_label_key: 'admin.dashboard.actions.assign_engineers',
      },
    ],
    release_payment: [
      {
        id: 'aq-pay-1',
        kind: 'release_payment',
        title: 'مشروع البناء الأول — مرحلة معتمدة',
        subtitle: 'الدفع جاهز للإفراج للمقاول',
        project_id: P001,
        milestone_id: 'm1',
        action_href: `/projects/${P001}/milestones/m1`,
        action_label_key: 'admin.dashboard.actions.release_payment',
      },
    ],
  },
  super_admin_flags: {
    pending_permission_requests: 2,
  },
  recent_projects: [
    {
      id: 'uuid-1',
      project_number: 'P001',
      name: 'مشروع البناء الأول',
      city: 'القاهرة',
      client_name: 'أحمد محمد',
      status: 'active',
      milestones_completed: 2,
      milestones_total: 5,
      progress_percentage: 40,
    },
    {
      id: 'uuid-2',
      project_number: 'P002',
      name: 'مشروع الإسكان الثاني',
      city: 'الجيزة',
      client_name: 'فاطمة علي',
      status: 'in_progress',
      milestones_completed: 3,
      milestones_total: 6,
      progress_percentage: 50,
    },
    {
      id: 'uuid-3',
      project_number: 'P003',
      name: 'مشروع المركز التجاري',
      city: 'الإسكندرية',
      client_name: 'محمد سالم',
      status: 'completed',
      milestones_completed: 4,
      milestones_total: 4,
      progress_percentage: 100,
    },
    {
      id: 'uuid-4',
      project_number: 'P004',
      name: 'مشروع العمارة السكنية',
      city: 'القاهرة',
      client_name: 'سارة خالد',
      status: 'active',
      milestones_completed: 1,
      milestones_total: 5,
      progress_percentage: 20,
    },
    {
      id: 'uuid-5',
      project_number: 'P005',
      name: 'مشروع المستشفى',
      city: 'الرياض',
      client_name: 'علي إبراهيم',
      status: 'under_review',
      milestones_completed: 0,
      milestones_total: 8,
      progress_percentage: 0,
    },
  ],
  open_disputes: [
    {
      id: 'dispute-1',
      dispute_number: 'D001',
      project_name: 'مشروع البناء الأول',
      requester_name: 'علي سالم',
      subject: 'تأخير في التسليم',
      status: 'open',
      created_at: '2026-05-08T10:30:00Z',
    },
    {
      id: 'dispute-2',
      dispute_number: 'D002',
      project_name: 'مشروع الإسكان الثاني',
      requester_name: 'نورا محمود',
      subject: 'عدم الامتثال للمواصفات',
      status: 'mediating',
      created_at: '2026-05-06T14:15:00Z',
    },
  ],
  activity_data: {
    months: [
      'يناير',
      'فبراير',
      'مارس',
      'أبريل',
      'مايو',
      'يونيو',
      'يوليو',
      'أغسطس',
      'سبتمبر',
      'أكتوبر',
      'نوفمبر',
      'ديسمبر',
    ],
    data: [
      { month: 'يناير', milestones: 5, projects: 2 },
      { month: 'فبراير', milestones: 8, projects: 3 },
      { month: 'مارس', milestones: 6, projects: 2 },
      { month: 'أبريل', milestones: 10, projects: 4 },
      { month: 'مايو', milestones: 12, projects: 3 },
      { month: 'يونيو', milestones: 9, projects: 2 },
      { month: 'يوليو', milestones: 14, projects: 5 },
      { month: 'أغسطس', milestones: 11, projects: 3 },
      { month: 'سبتمبر', milestones: 7, projects: 2 },
      { month: 'أكتوبر', milestones: 13, projects: 4 },
      { month: 'نوفمبر', milestones: 8, projects: 2 },
      { month: 'ديسمبر', milestones: 10, projects: 3 },
    ],
  },
  recent_events: [
    {
      id: 'event-1',
      type: 'project_created',
      title: 'مشروع جديد: مشروع البناء الأول',
      timestamp: '2026-05-09T15:30:00Z',
      related_entity_id: 'uuid-1',
      related_name: 'أحمد محمد',
    },
    {
      id: 'event-2',
      type: 'milestone_under_review',
      title: 'تقرير مرفوع للمراجعة',
      subtitle: 'الأساسات — مشروع البناء الأول',
      timestamp: '2026-05-09T12:00:00Z',
      related_entity_id: 'uuid-1',
      related_name: 'مشروع البناء الأول',
    },
    {
      id: 'event-3',
      type: 'milestone_approved',
      title: 'مرحلة معتمدة نهائياً',
      subtitle: 'الأساسات',
      timestamp: '2026-05-08T12:00:00Z',
      related_entity_id: 'uuid-1',
      related_name: 'مشروع البناء الأول',
    },
    {
      id: 'event-4',
      type: 'payment_released',
      title: 'تم الإفراج عن دفعة',
      subtitle: '50٬000 ج.م.',
      timestamp: '2026-05-07T10:45:00Z',
      related_entity_id: 'uuid-1',
      related_name: 'شركة البناء المتحدة',
    },
    {
      id: 'event-5',
      type: 'contractor_selected',
      title: 'تم اختيار مقاول للمشروع',
      subtitle: 'عمارة سكنية 6 طوابق',
      timestamp: '2026-05-06T18:00:00Z',
      related_entity_id: 'uuid-3',
      related_name: 'محمد حسن',
    },
    {
      id: 'event-6',
      type: 'bidding_opened',
      title: 'فتح باب العروض',
      subtitle: 'مركز صحي بالمنوفية',
      timestamp: '2026-05-06T09:20:00Z',
      related_entity_id: 'uuid-2',
    },
    {
      id: 'event-7',
      type: 'user_created',
      title: 'مستخدم جديد: مهندس موقع',
      timestamp: '2026-05-06T09:20:00Z',
      related_name: 'أحمد علي',
    },
    {
      id: 'event-8',
      type: 'milestone_approved',
      title: 'مرحلة معتمدة: الأعمال الكهربائية',
      timestamp: '2026-05-05T16:30:00Z',
      related_entity_id: 'uuid-2',
      related_name: 'مشروع الإسكان الثاني',
    },
    {
      id: 'event-9',
      type: 'project_created',
      title: 'مشروع جديد: مستودع صناعي',
      timestamp: '2026-05-04T11:00:00Z',
      related_name: 'عمرو الشرقاوي',
    },
    {
      id: 'event-10',
      type: 'milestone_under_review',
      title: 'بانتظار مراجعة المشرف',
      subtitle: 'الهيكل الخرساني',
      timestamp: '2026-05-03T08:00:00Z',
      related_name: 'مجمع تجاري بالجيزة',
    },
    {
      id: 'event-11',
      type: 'payment_released',
      title: 'إفراج دفع تلقائي',
      timestamp: '2026-05-02T14:00:00Z',
      related_name: 'مقاولون الشرق',
    },
  ],
}
