import type { AdminLovableOverview } from '~/shared/types/admin'

/** Static Lovable-aligned dashboard blocks; merge into mock GET /admin/dashboard until API ships. */
export const mockAdminLovableOverview: AdminLovableOverview = {
  alert_field_reports: 2,
  alert_new_project_requests: 1,
  primary_kpis: [
    {
      id: 'kpi-active-projects',
      title_key: 'admin.dashboard.lovable.primary.active_projects',
      value: 124,
      subtitle_key: 'admin.dashboard.lovable.primary.active_projects_sub',
      subtitle_params: { delta: 8 },
      icon: 'Building2',
      tone: 'success',
      href: '/projects',
      format: 'number',
    },
    {
      id: 'kpi-contractors',
      title_key: 'admin.dashboard.lovable.primary.contractors',
      value: 312,
      subtitle_key: 'admin.dashboard.lovable.primary.contractors_sub',
      subtitle_params: { delta: 12 },
      icon: 'Users',
      tone: 'primary',
      href: '/users?role=contractor',
      format: 'number',
    },
    {
      id: 'kpi-payments',
      title_key: 'admin.dashboard.lovable.primary.payments_volume',
      value: 8_400_000,
      subtitle_key: 'admin.dashboard.lovable.primary.payments_volume_sub',
      subtitle_params: { pct: 18 },
      icon: 'Coins',
      tone: 'warning',
      href: '/payments',
      format: 'compact_sar',
    },
    {
      id: 'kpi-disputes',
      title_key: 'admin.dashboard.lovable.primary.open_disputes',
      value: 7,
      subtitle_key: 'admin.dashboard.lovable.primary.open_disputes_sub',
      subtitle_params: { awaiting: 2 },
      icon: 'AlertTriangle',
      tone: 'danger',
      href: '/disputes',
      format: 'number',
    },
  ],
  sparkline_kpis: [
    {
      id: 'sp-new-projects-week',
      title_key: 'admin.dashboard.lovable.spark.new_projects_week',
      value_label_key: 'admin.dashboard.lovable.spark.plus_value',
      value_display_key:
        'admin.dashboard.lovable.spark.demo_new_projects_value',
      value_label_params: { value: 18 },
      series: [12, 14, 11, 16, 15, 18, 19],
      tone: 'warning',
      href: '/projects',
    },
    {
      id: 'sp-daily-booked',
      title_key: 'admin.dashboard.lovable.spark.daily_booked',
      value_label_key: 'admin.dashboard.lovable.spark.sar_compact',
      value_display_key: 'admin.dashboard.lovable.spark.demo_daily_sar',
      value_label_params: { value: 48_000 },
      series: [32, 36, 40, 38, 44, 46, 48],
      tone: 'warning',
      href: '/payments',
    },
    {
      id: 'sp-milestone-rate',
      title_key: 'admin.dashboard.lovable.spark.milestone_approval_rate',
      value_label_key: 'admin.dashboard.lovable.spark.percent_value',
      value_display_key: 'admin.dashboard.lovable.spark.demo_milestone_pct',
      value_label_params: { value: 92 },
      series: [88, 89, 90, 91, 90, 91, 92],
      tone: 'primary',
      href: '/projects',
    },
    {
      id: 'sp-csat',
      title_key: 'admin.dashboard.lovable.spark.csat',
      value_label_key: 'admin.dashboard.lovable.spark.rating_value',
      value_display_key: 'admin.dashboard.lovable.spark.demo_csat',
      value_label_params: { value: '4.7' },
      series: [4.2, 4.3, 4.5, 4.4, 4.6, 4.65, 4.7],
      tone: 'primary',
      href: '/users',
    },
  ],
  project_distribution: [
    {
      label_key: 'admin.dashboard.lovable.distribution.in_execution',
      percent: 63,
      color_class: 'bg-emerald-500',
    },
    {
      label_key: 'admin.dashboard.lovable.distribution.waiting_funding',
      percent: 19,
      color_class: 'bg-amber-500',
    },
    {
      label_key: 'admin.dashboard.lovable.distribution.waiting_assignment',
      percent: 11,
      color_class: 'bg-blue-500',
    },
    {
      label_key: 'admin.dashboard.lovable.distribution.paused',
      percent: 6,
      color_class: 'bg-red-500',
    },
  ],
  platform_activity: [
    { month: '2026-01', closed_projects: 4 },
    { month: '2026-02', closed_projects: 6 },
    { month: '2026-03', closed_projects: 5 },
    { month: '2026-04', closed_projects: 9 },
    { month: '2026-05', closed_projects: 11 },
    { month: '2026-06', closed_projects: 10 },
    { month: '2026-07', closed_projects: 13 },
    { month: '2026-08', closed_projects: 12 },
    { month: '2026-09', closed_projects: 14 },
    { month: '2026-10', closed_projects: 15 },
    { month: '2026-11', closed_projects: 16 },
    { month: '2026-12', closed_projects: 18 },
  ],
  latest_registrations: [
    {
      id: 'reg-1',
      name_key: 'admin.dashboard.lovable.demo_users.khaled',
      role_key: 'admin.dashboard.lovable.roles.supervisor_engineer',
      minutes_ago: 60,
    },
    {
      id: 'reg-2',
      name_key: 'admin.dashboard.lovable.demo_users.north_construction',
      role_key: 'admin.dashboard.lovable.roles.contractor',
      minutes_ago: 180,
    },
    {
      id: 'reg-3',
      name_key: 'admin.dashboard.lovable.demo_users.sara',
      role_key: 'admin.dashboard.lovable.roles.field_engineer',
      minutes_ago: 320,
    },
  ],
  weekly_registrations: [
    { role_key: 'admin.dashboard.lovable.roles.project_owner', count: 28 },
    { role_key: 'admin.dashboard.lovable.roles.contractor', count: 14 },
    { role_key: 'admin.dashboard.lovable.roles.supervisor_engineer', count: 8 },
    { role_key: 'admin.dashboard.lovable.roles.field_engineer', count: 12 },
  ],
  weekly_registrations_total: 62,
  weekly_registrations_delta_percent: 34,
}
